### ISSUE TITLE
[Suggestion] Editor fullscreen & toolbar

### ISSUE THREAD

**Issue by bleonard252** [OFFLINE-GmbH/Online-FTP-S3#11]
In the text editor, the Save and Download buttons overlap the text beneath. Putting them (and the fork me ribbon) in a toolbar would allow me to write to the text beneath the buttons and ribbon.

As well, I would like to have a fullscreen editor on desktop, using a button in aforementioned toolbar.

If this is not the place for suggestions, direct me to that place! Thank you in advance.

**Comment by tobias-kuendig** [comment]
We'll leave this open in case someone wants to submit a PR.
