### ISSUE TITLE
Url Parameters for pre-fill login form(FTP)

### ISSUE THREAD

**Issue by dafenix** [OFFLINE-GmbH/Online-FTP-S3#12]
hello,
it would be nice to pre-fill fields like "Host" or "Username" to simplify the login process. 

Example
`https://www.onlineftp.ch/?host=example.org&username=demo`

with kind regards
dafenix

**Comment by tobias-kuendig** [comment]
Great idea! Implemented in ee26beba133138bdfb2e10f98d23ec269ecd0192
