### ISSUE TITLE
Exhausted memory

### ISSUE THREAD

**Issue by iamface** [OFFLINE-GmbH/Online-FTP-S3#15]
Hi,
I have increased my max upload size to be 50 gig and am getting an exhausted memory allocation error. How much RAM does this application take to upload large files?

I am able to upload anything under a couple meg, but beyond that it fails.

```
# Online FTP
MAX_UPLOAD_SIZE=50000000 # in KB
```

Thanks.

**Comment by tobias-kuendig** [comment]
What excaclty is the error message?

The `MAX_UPLOAD_SIZE` config parameter only determines what the max filesize is that the application itself accepts. It does not set your `post_max_size`, `upload_max_filesize` or `memory_limit` php.ini settings. You'll have to increase these values as well.

**Comment by iamface** [comment]
I'm getting
`Allowed memory size of 134217728 bytes exhausted (tried to allocate 290517208 bytes)`

My `memory_limit` is at 128M, `post_max_size` and `upload_max_filesize` are both 5000M. I'm trying to upload a 120M file.

**Comment by tobias-kuendig** [comment]
As the error states your `memory_limit` is set too low. It needs to be at least around 300 MB to work for this upload.

**Comment by iamface** [comment]
Ah yep, you're right. I increased my memory limit and it uploaded. Thanks for the help!
