### ISSUE TITLE
404 Error

### ISSUE THREAD

**Issue by PlanetGamingGG** [OFFLINE-GmbH/Online-FTP-S3#16]
```
Not Found
The requested URL /login was not found on this server.
Apache/2.4.27 (Win64) PHP/7.0.23 Server at ftp.quid Port 80
```
That is what I get when I tried to login and gets redirected to http://domain/login.
I also can't find any .htaccess file's that will ussually fix this problem.

I am new to Laravel, please help me, thank you

**Comment by tobias-kuendig** [comment]
Make sure that you point your domain webroot to `/public`.
