### ISSUE TITLE
Blank page content after login

### ISSUE THREAD

**Issue by PlanetGamingGG** [OFFLINE-GmbH/Online-FTP-S3#17]
Hi,

The page content is blank after login and it took around 1 minute to login..
How can I debug this?
FYI I'm on localhost
![image](https://user-images.githubusercontent.com/35788716/38370915-788afd12-3915-11e8-9d27-72d806cd3774.png)

**Comment by PlanetGamingGG** [comment]
Also I got 404 error for css/app.css
I managed to copy it from your demo and it works fine untill I pointed my root directory to /public, which makes the framework treat it as route instead of CSS
![image](https://user-images.githubusercontent.com/35788716/38371123-dde28018-3915-11e8-9ee9-d4261d3a9e03.png)

**Comment by tobias-kuendig** [comment]
From the Readme:


> Installation
>    * Clone this repository to your machine.
>    * composer install
>    * yarn or npm install
>    * gulp or gulp --production

Did you run all these steps? In particular `gulp`?

**Comment by PlanetGamingGG** [comment]
The command
`npm install` and `yarn` give this error : 
`gyp verb check python checking for Python executable "python2" in the PATH
gyp verb `which` failed Error: not found: python2
gyp verb `which` failed     at getNotFoundError (C:\Windows\System32\composer-file\node_modules\which\which.js:13:12)
gyp verb `which` failed     at F (C:\Windows\System32\composer-file\node_modules\which\which.js:68:19)
gyp verb `which` failed     at E (C:\Windows\System32\composer-file\node_modules\which\which.js:80:29)
gyp verb `which` failed     at C:\Windows\System32\composer-file\node_modules\which\which.js:89:16
gyp verb `which` failed     at C:\Windows\System32\composer-file\node_modules\isexe\index.js:42:5
gyp verb `which` failed     at C:\Windows\System32\composer-file\node_modules\isexe\windows.js:36:5
gyp verb `which` failed     at FSReqWrap.oncomplete (fs.js:170:21)
gyp verb `which` failed  python2 { Error: not found: python2
gyp verb `which` failed     at getNotFoundError (C:\Windows\System32\composer-file\node_modules\which\which.js:13:12)
gyp verb `which` failed     at F (C:\Windows\System32\composer-file\node_modules\which\which.js:68:19)
gyp verb `which` failed     at E (C:\Windows\System32\composer-file\node_modules\which\which.js:80:29)
gyp verb `which` failed     at C:\Windows\System32\composer-file\node_modules\which\which.js:89:16
gyp verb `which` failed     at C:\Windows\System32\composer-file\node_modules\isexe\index.js:42:5
gyp verb `which` failed     at C:\Windows\System32\composer-file\node_modules\isexe\windows.js:36:5
gyp verb `which` failed     at FSReqWrap.oncomplete (fs.js:170:21)
gyp verb `which` failed   stack: 'Error: not found: python2\n    at getNotFoundError (C:\\Windows\\System32\\composer-file\\node_modules\\which\\which.js:13:12)\n    at F (C:\\Windows\\System32\\composer-file\\node_modules\\which\\which.js:68:19)\n    at E (C:\\Windows\\System32\\composer-file\\node_modules\\which\\which.js:80:29)\n    at C:\\Windows\\System32\\composer-file\\node_modules\\which\\which.js:89:16\n    at C:\\Windows\\System32\\composer-file\\node_modules\\isexe\\index.js:42:5\n    at C:\\Windows\\System32\\composer-file\\node_modules\\isexe\\windows.js:36:5\n    at FSReqWrap.oncomplete (fs.js:170:21)',
gyp verb `which` failed   code: 'ENOENT' }
gyp verb check python checking for Python executable "python" in the PATH
gyp verb `which` failed Error: not found: python
gyp verb `which` failed     at getNotFoundError (C:\Windows\System32\composer-file\node_modules\which\which.js:13:12)
gyp verb `which` failed     at F (C:\Windows\System32\composer-file\node_modules\which\which.js:68:19)
gyp verb `which` failed     at E (C:\Windows\System32\composer-file\node_modules\which\which.js:80:29)
gyp verb `which` failed     at C:\Windows\System32\composer-file\node_modules\which\which.js:89:16
gyp verb `which` failed     at C:\Windows\System32\composer-file\node_modules\isexe\index.js:42:5
gyp verb `which` failed     at C:\Windows\System32\composer-file\node_modules\isexe\windows.js:36:5
gyp verb `which` failed     at FSReqWrap.oncomplete (fs.js:170:21)
gyp verb `which` failed  python { Error: not found: python
gyp verb `which` failed     at getNotFoundError (C:\Windows\System32\composer-file\node_modules\which\which.js:13:12)
gyp verb `which` failed     at F (C:\Windows\System32\composer-file\node_modules\which\which.js:68:19)
gyp verb `which` failed     at E (C:\Windows\System32\composer-file\node_modules\which\which.js:80:29)
gyp verb `which` failed     at C:\Windows\System32\composer-file\node_modules\which\which.js:89:16
gyp verb `which` failed     at C:\Windows\System32\composer-file\node_modules\isexe\index.js:42:5
gyp verb `which` failed     at C:\Windows\System32\composer-file\node_modules\isexe\windows.js:36:5
gyp verb `which` failed     at FSReqWrap.oncomplete (fs.js:170:21)
gyp verb `which` failed   stack: 'Error: not found: python\n    at getNotFoundError (C:\\Windows\\System32\\composer-file\\node_modules\\which\\which.js:13:12)\n    at F (C:\\Windows\\System32\\composer-file\\node_modules\\which\\which.js:68:19)\n    at E (C:\\Windows\\System32\\composer-file\\node_modules\\which\\which.js:80:29)\n    at C:\\Windows\\System32\\composer-file\\node_modules\\which\\which.js:89:16\n    at C:\\Windows\\System32\\composer-file\\node_modules\\isexe\\index.js:42:5\n    at C:\\Windows\\System32\\composer-file\\node_modules\\isexe\\windows.js:36:5\n    at FSReqWrap.oncomplete (fs.js:170:21)',
gyp verb `which` failed   code: 'ENOENT' }
gyp verb could not find "python". checking python launcher
gyp verb could not find "python". guessing location
gyp verb ensuring that file exists: C:\Python27\python.exe
gyp ERR! configure error
gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
gyp ERR! stack     at PythonFinder.failNoPython (C:\Windows\System32\composer-file\node_modules\node-gyp\lib\configure.js:483:19)
gyp ERR! stack     at PythonFinder.<anonymous> (C:\Windows\System32\composer-file\node_modules\node-gyp\lib\configure.js:508:16)
gyp ERR! stack     at C:\Windows\System32\composer-file\node_modules\graceful-fs\polyfills.js:284:29
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:170:21)
gyp ERR! System Windows_NT 10.0.16299
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Windows\\System32\\composer-file\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd C:\Windows\System32\composer-file\node_modules\node-sass
gyp ERR! node -v v9.11.1
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
Build failed with error code: 1
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.3 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-sass@3.13.1 postinstall: `node scripts/build.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-sass@3.13.1 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\User\AppData\Roaming\npm-cache\_logs\2018-04-07T01_23_08_218Z-debug.log`

Do I need python from https://www.python.org/ ?
or is there something Im missing?

Full debug log : 
[2018-04-07T01_23_08_218Z-debug.log](https://github.com/OFFLINE-GmbH/Online-FTP-S3/files/1885946/2018-04-07T01_23_08_218Z-debug.log)


Thanks for the help (In advance)!

**Comment by PlanetGamingGG** [comment]
Okay, I saw this error : 
`C:\Python27\Python.exe: can't open file 'C:\Windows\System32\composer-file\node_modules\node-gyp\gyp\gyp_main.py': [Errno 2] No such file or directory
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onCpExit (C:\Windows\System32\composer-file\node_modules\node-gyp\lib\configure.js:336:16)
gyp ERR! stack     at ChildProcess.emit (events.js:180:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:12)
gyp ERR! System Windows_NT 10.0.16299
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Windows\\System32\\composer-file\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd C:\Windows\System32\composer-file\node_modules\node-sass
gyp ERR! node -v v9.11.1
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
Build failed with error code: 1
npm WARN rollback Rolling back minimist@1.2.0 failed (this is probably harmless): EPERM: operation not permitted, scandir 'C:\Windows\System32\composer-file\node_modules\fsevents\node_modules\rc\node_modules'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.3 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-sass@3.13.1 postinstall: `node scripts/build.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-sass@3.13.1 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\User\AppData\Roaming\npm-cache\_logs\2018-04-08T11_42_20_162Z-debug.log`

Log file : 
[2018-04-08T11_42_20_162Z-debug.log](https://github.com/OFFLINE-GmbH/Online-FTP-S3/files/1887394/2018-04-08T11_42_20_162Z-debug.log)


I belive this might have caused it : 
`Downloading binary from https://github.com/sass/node-sass/releases/download/v3.13.1/win32-x64-59_binding.node
Cannot download "https://github.com/sass/node-sass/releases/download/v3.13.1/win32-x64-59_binding.node":

HTTP error 404 Not Found

Hint: If github.com is not accessible in your location
      try setting a proxy via HTTP_PROXY, e.g.

      export HTTP_PROXY=http://example.com:1234

or configure npm proxy via

      npm config set proxy http://example.com:8080`

The URL given give's 404 error on regular browser too..
How can I change the URL?

**Comment by PlanetGamingGG** [comment]
After installing python and running the npm install command, I saw the errors above.
Still stuck here...

**Comment by tobias-kuendig** [comment]
Yes, I understand. But this problem has nothing to do with this project. The problem is your local npm setup. I cannot help you here any further but Google should point you in the right direction.

I just tried to compile the assets locally and everything is working as it should. Download this zip and extract it to `public/`. These are the compiled assets.

https://transfer.sh/WnEOM/public.zip
