### ISSUE TITLE
Annoying Buttons

### ISSUE THREAD

**Issue by Filip9696** [OFFLINE-GmbH/Online-FTP-S3#18]
These buttons are really annoying because they wont let you click on the things behind them such as the scroll bar.
The bottom scroll bar is completely inaccessible
![image](https://user-images.githubusercontent.com/27921728/39450091-1f44f64a-4c98-11e8-8e3f-9da7162fa05d.png)

![image](https://user-images.githubusercontent.com/27921728/39450050-f45cec08-4c97-11e8-8515-ba20ec32eb5c.png)

**Comment by tobias-kuendig** [comment]
Thank you for your input. This issue is already reportet in https://github.com/OFFLINE-GmbH/Online-FTP-S3/issues/11. 

Feel free to submit a PR!
