### ISSUE TITLE
Install on Ubuntu

### ISSUE THREAD

**Issue by AntMon1993** [OFFLINE-GmbH/Online-FTP-S3#20]
Don't know what other to do.

1 - Ubuntu clean installation
2 - Lamp installed (it didn't ask me Mysql Pass...strange)
3 - Install Composer
4 - Install and Test Laravel
5 - Copy Release 1.0.4 source codes in main folder /var/www/html/
6 - Renamed .env.example in .env
7 - Run composer install (all seems to work)

Open localhost and it's like missing the .css files and, when i try to log, the login script page doesn't exists. It seems as only index page is correctly installed (i can see the blue background but all the inputs are messy)...

i'm new to composer and laravel, is there something i skipped during installation?
ps: is Mysql necessary to run this app?

**Comment by tobias-kuendig** [comment]
You did everything except the official [installation steps mentioned in the README](https://github.com/OFFLINE-GmbH/Online-FTP-S3#installation)? :wink: 

You'll have to compile the assets with `npm install` then `./node_modules/.bin/gulp --production`.

Alternatively grab these two files and put them to `public/js/app.js` and `public/css/app.css` on your server.

https://onlineftp.ch/js/app.js
https://onlineftp.ch/css/app.css

**Comment by AntMon1993** [comment]
Okok, with these two files I solved the of graphics issue, obviously.
However, i still have a 404 page after logging in ...

**Comment by tobias-kuendig** [comment]
If you are running apache make sure to configure it correctly to work with Laravel. You'll find many tutorials on how to do this online:

https://www.howtoforge.com/tutorial/install-laravel-on-ubuntu-for-apache/

**Comment by AntMon1993** [comment]
Mmm i've followed this tutorial and now, after a new clean installation, it works! Maybe it was the "rewrite mode" in apache setting...
Last question: is there any possibility to install/translate a new language? I mean with all errors/exception translated ecc

**Comment by tobias-kuendig** [comment]
Great! You currently cannot translate the GUI dynamically. You cab edit the sourcefile and build everything yourself but I wouldn't suggest that.
