### ISSUE TITLE
How to run the project?

### ISSUE THREAD

**Issue by sparkk29** [OFFLINE-GmbH/Online-FTP-S3#21]
I have installed everything as shown on the readme installation. I am trying this on the server. I have no prior knowledge of php or laravel. 

1. cloned repo
2. installed composer 
3. installed laravel
4 npm install and then gulp --production

Please help me.

**Comment by sparkk29** [comment]
getting this:
Failed to load resource: the server responded with a status of 500 (Internal Server Error)

**Comment by tobias-kuendig** [comment]
> I have no prior knowledge of php or laravel.

Well, this might be a problem. Check our webserver's error logs to find more information about the internal server error.

**Comment by sparkk29** [comment]
okay thanks, I got to work after re-doing every step till I got it right. thanks

**Comment by sparkk29** [comment]
okay thanks, I got to work after re-doing every step till I got it right. thanks
