### ISSUE TITLE
Not able to change PATH? And what should be the default PATH?

### ISSUE THREAD

**Issue by sparkk29** [OFFLINE-GmbH/Online-FTP-S3#22]
after logging in I am getting this error.
error: 'Cannot fetch files for /'

P.S.: I tried changing PATH at 'resources/assets/js/store/index.js', but it didn't work.

**Comment by sparkk29** [comment]
<a href="https://ibb.co/nkwKry"><img src="https://thumb.ibb.co/nkwKry/Screen_Shot_2018_07_18_at_6_15_28_PM.png" alt="Screen_Shot_2018_07_18_at_6_15_28_PM" border="0"></a>

**Comment by tobias-kuendig** [comment]
You'll have to show me some more information. What URL does get a 404? Do you find something in your `storage/logs/laravel.log` file?

**Comment by sparkk29** [comment]
nothing is on storage/logs/laravel.log file, it's all yesterdays errors only, which got solved.
This is what I am getting.
app.js:5 GET http://MYIP/directory/?path= 404 (Not Found)
app.js:7 t {url: "/directory/?path=", ok: false, status: 404, statusText: "Not Found", headers: t, …}

I think the url where the API is calling is not correct. 
my project is at /var/www/html/nc/online-FTP/Online-FTP-S3-1.0.4/MyProject/ and not /var/www/html/

**Comment by tobias-kuendig** [comment]
You'll have to debug this yourself since the information provided is not enough for me to help.

Check your webserver's error log. See if the Laravel application is even reached or if the 404 error is generated by the webserver itself.

**Comment by sparkk29** [comment]
Thanks for helping.
