### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by jwhulette** [OFFLINE-GmbH/Online-FTP-S3#24]
I have written a Laravel plugin based on your code.
I don't see a license for you code so I'm not sure I can publish the repo publicly. 
I have acknowledged this repo in the Readme, stating that my codes is based off yours. 
Do you have an issue with my release my code under MIT license publicly?

**Comment by tobias-kuendig** [comment]
Hi @jwhulette 

Thank you for bringing this up. The project is licensed under MIT, I have added the appropriate license information to the repository.
