### ISSUE TITLE
How to install in Ubuntu Server???

### ISSUE THREAD

**Issue by eprompc** [OFFLINE-GmbH/Online-FTP-S3#3]
How can we install it on ubuntu server ???

**Comment by tobias-kuendig** [comment]
1. Install PHP 7 and a webserver like nginx or apache. You'll find [information on how to do that all over the internet](https://www.digitalocean.com/community/tutorials/how-to-upgrade-to-php-7-on-ubuntu-14-04).
2. Download [a pre built release](https://github.com/OFFLINE-GmbH/Online-FTP-S3/releases) or build the project your self as described in the readme
3. That's it
