### ISSUE TITLE
Donation?

### ISSUE THREAD

**Issue by eddiethejibson** [OFFLINE-GmbH/Online-FTP-S3#4]
Hi,

I'd like to make a donation, helped me a lot. Any chance you have a paypal.me link?

Cheers.

**Comment by ekandreas** [comment]
;-)

Thanks!

paypal.me/ekandreas <http://paypal.me/ekandreas>

Regards, Andreas Ek, +46703032203

**Comment by tobias-kuendig** [comment]
@eddiethejibson, thanks for this kind gesture but we currently do not take any donations. I'm glad our project was of use to you!
