### ISSUE TITLE
How to run this app ? ;)

### ISSUE THREAD

**Issue by wrkilu** [OFFLINE-GmbH/Online-FTP-S3#47]
Hi,
Running JS app as server is not so obvious on Linux ;)
Could you write how to run this app on Linux after installation ?

My install went good I think. I've made steps:
composer install
npm install
npm run prod
and all went without errors. But how to run that app now ? And what URL should I type in browser ?

Thank you DEV!

**Comment by tobias-kuendig** [comment]
You need a webserver that serves php. Alternatively you can run `php artisan serve` locally to get a single php integrated webserver.

**Comment by wrkilu** [comment]
Oh I've found solution myself so let me add it for others and perhaps to documentation.
In Apache you have to point out folder for it e.g.
/var/www/html/Online-FTP-S3/public
Other seeings in virtual host file - default.
Cheers.
