### ISSUE TITLE
Package

### ISSUE THREAD

**Issue by exwizzard** [OFFLINE-GmbH/Online-FTP-S3#5]
Any chance to move this into a package that we can install via composer into existing projects?

If not, any tips on how to integrate into existing laravel project?

**Comment by tobias-kuendig** [comment]
There are currently no plans to create a separate package. The laravel part of online ftp is essentialy only a nice rest api wrapper around the built in filesystem features. Check out the `Transfer`, `Repositories`, `Helpers` and `Controllers` folders. It's not that much code to port into an existing project. 

All of the frontend is stored under `resources/assets/js/`.
