### ISSUE TITLE
TypeError: Vue.http is undefined

### ISSUE THREAD

**Issue by willruss1** [OFFLINE-GmbH/Online-FTP-S3#7]
Followed the instructions as well as I know how, and all seems functional with the login view, and with connections to the FTP host on the backend (I'm the admin there, too), but getting an odd error that I'm not sure how to go about resolving. 

After login, it just shows a blank white page. There are no errors in either apache or ftp logs. The dev tools on the browser window shows the following:

![screenshot from 2017-09-07 16-57-13](https://user-images.githubusercontent.com/3075784/30187089-c9ab2a3c-93ed-11e7-88b1-8cad0dfa5d84.png)

The node module for vue seems to be installed:
```
root@phoebe:/var/www/webftp/node_modules# ll | grep vue
drwxr-xr-x   2 www-data www-data  4096 Sep  7 14:24 laravel-elixir-vue-2/
drwxr-xr-x   5 www-data www-data  4096 Sep  7 14:25 vue/
drwxr-xr-x   2 www-data www-data  4096 Sep  7 14:25 vue-hot-reload-api/
drwxr-xr-x   3 www-data www-data  4096 Sep  7 14:25 vue-loader/
drwxr-xr-x   8 www-data www-data  4096 Sep  7 14:25 vue-resource/
drwxr-xr-x   2 www-data www-data  4096 Sep  7 14:25 vue-style-loader/
drwxr-xr-x   2 www-data www-data  4096 Sep  7 14:25 vue-template-compiler/
drwxr-xr-x   2 www-data www-data  4096 Sep  7 14:25 vue-template-es2015-compiler/
drwxr-xr-x   4 www-data www-data  4096 Sep  7 14:25 vuex/
```

I'm no developer, php or .js or otherwise, just a humble sysadmin. I'm not sure what I'm missing. Any help would be appreciated.

**Comment by tobias-kuendig** [comment]
Thanks for pointing that out. When using `npm` to install the packages a newer version of vue-resource was installed where the API has changed.

To fix the problem simply change this line:
https://github.com/OFFLINE-GmbH/Online-FTP-S3/commit/4515956a785f6e41f9ff45a9343f92088ef4e3ab

Then delete your `node_modules` folder, rerun `npm install` and finally `gulp --production`  to get everything up and running.
