### ISSUE TITLE
Uploading from Windows, cannot judge zip extension?

### ISSUE THREAD

**Issue by corselia** [OFFLINE-GmbH/Online-FTP-S3#8]
Thank you for great product, Online-FTP-S3 :)

btw, zip extract function is not available by uploading from Windows although Linux (Ubuntu) is okay.
thus I changed `saveTempFiles` method at [UploadTransfer.php](https://github.com/OFFLINE-GmbH/Online-FTP-S3/blob/d47084595169208c5c89e5419006fada7215bb5c/app/Transfer/Upload/UploadTransfer.php) as below.

```php
            /** @var $file UploadedFile */
            if ($extract === true) {
                (new Zipper())->unzip($file->getRealPath(), $base);
            } else {
                $file->move($base, $file->getClientOriginalName());
            }

```

this enables to extract zip correctly.
yeah, indeed this occurs to extract file with any extension if checkbox is on ;-(

this problem is based on Windows? or others?
and how to solve this?

Sincerely,

**Comment by tobias-kuendig** [comment]
Do you upload from Windows to Ubuntu (Server) or from Ubuntu to Windows (Server)?

It should not matter from what OS you are uploading the file. It can make a difference on the server though. 

If you add a `dd($file->clientExtension());` or `dd($file);` before [this line](https://github.com/OFFLINE-GmbH/Online-FTP-S3/blob/d47084595169208c5c89e5419006fada7215bb5c/app/Transfer/Upload/UploadTransfer.php#L75) what output do you get when you upload your file?

**Comment by corselia** [comment]
@tobias-kuendig 

thank you for quick response! and sorry for lack of descripiton.
my environment is below.

- Server OS is Linux (Ubuntu 16.04 LTS)
- Client OS is Windows 7 and Linux (Ubuntu 16.04 LTS)
- Client web browser is Chrome and Firefox
    - On Windows, unavailable by both browsers
    - On Linux, available by both browsers

certainly I also guess OS doesn't matter. I try test codes you show as soon as possible.

please wait a little :smiley:

**Comment by corselia** [comment]
sorry for late response.

I tried your idea. so I could upload file correctly and app doesn't show dump and doesn't die (`Upload successful` is displayed).

environment:
- OS
    - Windows 7
    - Ubuntu
- Web browser
    - Chrome
    - Firefox
- file extension
    - zip
    - not zip

I tried all combinations. result is the same.

I doubt `php.ini` settings...

**Comment by tobias-kuendig** [comment]
Yes, that's because it's an AJAX request. The dump will only be visible in the developer tools in the Network tab. Look there.

Alternatively you can add a `info` statement and then look in your log files for the output.

```php
info('Uploading file', ['file' => $file, 'extension' => $file->clientExtension()]);
```

**Comment by corselia** [comment]
oh, thanks! soon i tried again. below is log by `info`.

#### `Windows 7`, `Chrome` and `zip extension file`

```
[2017-10-19 07:13:27] production.INFO: Uploading file {"file":"[object] (Illuminate\\Http\\UploadedFile: /tmp/phpYyl9wn)","extension":null} 
```

#### `Windows 7`, `Chrome` and `txt extension file`

```
[2017-10-19 07:19:09] production.INFO: Uploading file {"file":"[object] (Illuminate\\Http\\UploadedFile: /tmp/phpaiXIU5)","extension":"txt"} 
```

#### `Ubuntu 16.04 LTS`, `Chrome` and `zip extension file`

```
[2017-10-19 07:17:20] production.INFO: Uploading file {"file":"[object] (Illuminate\\Http\\UploadedFile: /tmp/phpzq55cC)","extension":"zip"} 
```

#### `Ubuntu 16.04 LTS`, `Chrome` and `txt extension file`

```
[2017-10-19 07:28:58] production.INFO: Uploading file {"file":"[object] (Illuminate\\Http\\UploadedFile: /tmp/phpxyT9m2)","extension":"txt"} 
```

in Firefox, the same result.

**Comment by tobias-kuendig** [comment]
Could you replace the info statement with the following and provide me with the log entry when you upload the zip file on Windows again?

```php
info('Uploading file', ['mime' => $file-> getMimeType(), 'extension' => $file->getExtension(), 'guessed' => $file->guessExtension()]);
```

**Comment by corselia** [comment]
I replaced the statement.

```
[2017-10-19 08:26:41] production.INFO: Uploading file {"mime":"text/plain","extension":"","guessed":"txt"} 
[2017-10-19 08:26:49] production.INFO: Uploading file {"mime":"application/zip","extension":"","guessed":"zip"} 
```

the former file is `txt` extension. the latter is `zip` extension.

**Comment by tobias-kuendig** [comment]
Thank you! This change should fix the issue:

https://github.com/OFFLINE-GmbH/Online-FTP-S3/pull/10/commits/c09a6620b16cff935bfd40df3ac9a012627a9e89

You can apply it manually or [use the latest release](https://github.com/OFFLINE-GmbH/Online-FTP-S3/releases/tag/v1.0.4) to update.

**Comment by corselia** [comment]
@tobias-kuendig 

Great. thank you for this awesome product, me too. I'm glad to contribute. :smile:
